vega/vega-embed

README.md

- Add API description for opt parameter in function call and mode parameter inside opt

Update to include opt and mode

---

src/embed.js
test.html

`actions` in `opt` argument of `embed` is not working properly.

Actions should get default values correctly.

---

README.md

complete the documentation of `opt.config`

---

README.md
src/embed.js

Optional loader. Fixes #33

---

src/embed.ts
src/post.ts

**Post renderer to editor**
- Posting renderer along with mode and spec to the editor.
- On the way to fixing [this](https://github.com/vega/editor/issues/51).

Post renderer to editor

---

src/embed.ts
src/post.ts

**Post config to editor**
- Sending config along with other data to the editor.
- Fixes #65.

Post config to editor

---

src/post.ts

This is causing error when running vega-lite documentation website. 
cc: @ydlamba

Make config and renderer in post optional

---

.gitignore
.prettierrc.json
.travis.yml
package.json
rollup.config.js
src/embed.ts
src/index.ts
src/post.ts
test-vg.html
test-vl.html
tsconfig.json
yarn.lock

Trying to fix https://github.com/observablehq/vega/issues/8#issuecomment-378389907

Use rollup

---

README.md

removed extra : from README

---

src/embed.ts

Now correctly reports with the user provided selector string.

fix backtik typo

---

src/embed.ts

fix: switch to click

---

README.md
package.json
src/embed.ts
test-vg.html
test/embed.test.ts
yarn.lock

fixes #467
Also improving the docs a bit along the way.

feat: support AST and expression interpreter

---

.github/workflows/test.yml

Turns out, it's faster overall.

ci: remove caching

---

vega-embed.scss

fix: change overflow scroll to auto

---

src/embed.ts
test/embed.test.ts

fix: support loader options in usermeta

---

README.md
src/embed.ts

feat: custom View class and renderer

---

package.json
src/embed.ts

fix: set correct wrapper classes when there are autosize signals

---

build-style.sh

fix: update style generation script

---

.github/workflows/publish.yml
package.json

<details>
<summary>📦 Published PR as canary version: <code>6.20.3--canary.795.9a81b8f.0</code></summary>
<br />
```bash
npm install vega-embed@6.20.3--canary.795.9a81b8f.0
yarn add vega-embed@6.20.3--canary.795.9a81b8f.0
```
</details>

ci: simplify publishing

---

src/embed.ts

feat!: set default renderer to SVG

---

src/embed.ts

feat!: set default renderer to SVG (#680)

---

.github/workflows/merge-dependabot.yml

Makes what happens more explicit.

ci: use dependabot/fetch-metadata

---

README.md

docs: update default for renderer
