- package.json
- src/embed.js
- test/resources/embed-world.json
This PR adds, depending on the renderer specified, an "Export As PNG/SVG" action. The `actions` property of an embedding specification has also been expanded to selectively disable some actions to allow more flexibility.
> Export Action

- .eslintrc
- README.md
- src/embed.js
Following #34 
`eslint` returns 
```
/Users/younghoonkim/Desktop/dev/vega-embed/src/embed.js
193:10  error  'Promise' is not defined  no-undef
214:14  error  'Promise' is not defined  no-undef
✖ 2 problems (2 errors, 0 warnings)
```
> Changed let and const to var

- .gitignore
**Update .gitignore for yarn logs**
- This PR updates `.gitignore` to ignore debug and error logs generated by yarn/npm.
> Update .gitignore for debug and error logs

- .npmignore
- .travis.yml
- README.md
- package.json
- rollup.config.js
- src/container.ts
- src/embed.ts
- src/index.ts
- test-container.html
- test/container.test.ts
- test/embed.test.ts
- tsconfig.json
- typings/css.d.ts
- vega-embed-container.css
- vega-embed.css
- yarn.lock
As suggested by @mbostock this PR adds support for Observable to Vega-Embed. 
Demo is at https://beta.observablehq.com/@domoritz/vega-lite-in-observable-vega-embed
When this is merged and released, you will be able to run this in Observable:
```js
embed = require("vega-embed")
viewof view = embed(spec)
```
Note that one limitation of the wrapper approach (which wraps `vegaEmbed.container` and `vegaEmbed.embed` in a single function that automatically redirects) is that the first argument to `container` cannot be a URL that points to a spec. However, this is not a common case. Moreover, we require people to specify the type of spec (no separate function for Vega and Vega-Lite). In the existing observable modules, there are separate packages for Vega and Vega-Lite. I added some code to …
> Observable compatible Vega-Embed.

- package.json
- src/embed.ts
- src/index.ts
- test-container.html
- yarn.lock
Replace d3 select with native document functions to lighten package. #212
> Remove d3 select.

- src/embed.ts
Fixes #270
My leak test spec
```html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>Vega-Embed for Vega</title>
<script src="https://cdn.jsdelivr.net/npm/vega@5.8.1"></script>
<script src="build/vega-embed.js"></script>
</head>
<body>
<div id="vis"></div>
<script>
const spec = {
$schema: "https://vega.github.io/schema/vega/v5.json",
width: 400,
height: 200,
padding: 5,
data: [
{
name: "table",
values: [
{ category: "A", amount: 28 },
{ category: "B", amount: 55 },
{ category: "C", amount: 43 },
{ category: "D", amount: 91 },
{ category: "E", amount: 81 },
{ category: "F", amount: 53 },
{ category: "G", amount: 19 },
{ category: "H", amount: 87 }
]
}
],
signals: [
{
name: "tooltip",
value: {},
on: [
{ …
```
> Remove document click event listener on finalize.

- src/index.ts
Webpack no longer supports using named exports from JSON modules (https://webpack.js.org/migrate/5/#cleanup-the-code)
It looks like a similar update was made in vega-lite here https://github.com/vega/vega-lite/pull/7029
> refactor: import only default from JSON files for webpack 5

- package.json
- rollup.config.js
- yarn.lock
This addresses #684. I verified that the newly compiled es5 build works in IE 11.  
**Changes:**
- Switched rollup to previous version to get around build issue
- Added babel preset config to rollup config so that it doesn't use the babel.config.js config used for jest
FWIW, here's the JS and polyfills I had to use:
```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/babel-polyfill/7.4.4/polyfill.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/whatwg-fetch@3.0.0/dist/fetch.umd.min.js"></script>
<script src="https://unpkg.com/@webcomponents/webcomponentsjs@2.5.0/bundles/webcomponents-sd.js"></script>
<script src="https://cdn.jsdelivr.net/npm/vega@5/build-es5/vega.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/vega-lite@4/build-es5/vega-lite.min.js"></script> …
```
> fix: use babel preset config to support es5

- .autorc.json
- .github/workflows/merge-dependabot.yml
- .github/workflows/publish.yml
- .github/workflows/test.yml
- README.md
- package.json
- yarn.lock
- Less time spent on managing package infra 
- Replicate the setup in https://github.com/vega/vega-themes/pull/293, + updates documentation
- CI should pass
- I was initially getting a cryptic error message about the inability to set the `NPM_TOKEN`, followed by an authentication error. I tried setting *just* `NPM_TOKEN` or `NODE_AUTH_TOKEN` (which works for all the other repos), but for some reason the command fails unless you use both. Switching back to Node 14 (from the current 15) doesn't seem to make a difference. 
- It turns out when you `yarn run`, it quietly changes the package registry to yarnpkg instead of npmjs (as reported https://github.com/yarnpkg/yarn/issues/5854 ). After trying a few different "workarounds" and gradually increasing logging verbosity, I found the most …
> chore: set up auto for versioning/release management 

- build-style.sh
- package.json
- yarn.lock
<details>
<summary>📦 Published PR as canary version: <code>6.20.1--canary.784.ef30049.0</code></summary>
<br />
```bash
npm install vega-embed@6.20.1--canary.784.ef30049.0
yarn add vega-embed@6.20.1--canary.784.ef30049.0
```
</details>
> chore: switch to new sass version

- test/embed.test.ts
Relevant to https://github.com/vega/vega-embed/issues/767
<details>
<summary>📦 Published PR as canary version: <code>6.20.1--canary.789.594be07.0</code></summary>
<br />
```bash
npm install vega-embed@6.20.1--canary.789.594be07.0
yarn add vega-embed@6.20.1--canary.789.594be07.0
```
</details>
> test: no warnings when versions are compatible

- src/embed.ts
Fixes #767
<details>
<summary>📦 Published PR as canary version: <code>6.20.1--canary.790.70fb595.0</code></summary>
<br />
```bash
npm install vega-embed@6.20.1--canary.790.70fb595.0
yarn add vega-embed@6.20.1--canary.790.70fb595.0
```
</details>
> fix: fix build with semver

- package.json
- patches/yallist+4.0.0.patch
- yarn.lock
fixes #780
<details>
<summary>📦 Published PR as canary version: <code>6.20.3--canary.800.06c796e.0</code></summary>
<br />
```bash
npm install vega-embed@6.20.3--canary.800.06c796e.0
yarn add vega-embed@6.20.3--canary.800.06c796e.0
```
</details>
> fix: inline yallist iterator patch

- package.json
Otherwise packages can't easily apply the patch.
> fix: use npm for postinstall

- package.json
Fixes #806
<details>
<summary>📦 Published PR as canary version: <code>6.20.5--canary.807.4b66f40.0</code></summary>
<br />
```bash
npm install vega-embed@6.20.5--canary.807.4b66f40.0
yarn add vega-embed@6.20.5--canary.807.4b66f40.0
```
</details>
> fix: try bundledDependencies

- vega-embed.scss
Built off of https://github.com/vega/vega-embed/pull/839 by @benhammondmusic. 
Chrome: 
https://user-images.githubusercontent.com/589034/150186375-0c283708-6310-4c83-9fb7-1617e3aac67f.mov
Safari:
https://user-images.githubusercontent.com/589034/150186402-1a724fa3-ce50-49f5-bc0f-298ada8e947c.mov
<details>
<summary>📦 Published PR as canary version: <code>6.20.6--canary.841.78ab2d1.0</code></summary>
<br />
```bash
npm install vega-embed@6.20.6--canary.841.78ab2d1.0
yarn add vega-embed@6.20.6--canary.841.78ab2d1.0
```
</details>
> fix: add visible focus state to actions menu for A11y

- src/embed.ts
fixes #856
<details>
<summary>📦 Published PR as canary version: <code>6.20.7--canary.858.b5b98aa.0</code></summary>
<br />
```bash
npm install vega-embed@6.20.7--canary.858.b5b98aa.0
yarn add vega-embed@6.20.7--canary.858.b5b98aa.0
```
</details>
> fix: use innerHTML to set style to avoid <br>

- README.md
- src/embed.ts
- src/types.ts
- test/embed.test.ts
Exposes `vega.expressionFunction` to allow consumers to create custom functions/formatters.
Follow up to this ticket: https://github.com/vega/vega-embed/issues/934
> feat: Expose expression functions

- README.md
Hi! 👋 
This PR serves to add `Number` to the supported types of the `padding` property, as well as to explicitly mention that the installed Yarn version must be Yarn 1 due to the way the `package.json` scripts are prepared. 
Hope it's helpful. Let me know what you think of this PR!
References:
- https://yarnpkg.com/advanced/lifecycle-scripts
- https://classic.yarnpkg.com/en/docs/package-json#toc-scripts
> fix(docs): update `padding` type and mention the Yarn version

- package.json
- rollup.config.mjs
before: Created bundle vega-embed.module.js: 114.94 kB → 29.03 kB (gzip)
after: Created bundle vega-embed.module.js: 76.41 kB → 20.25 kB (gzip)
fixes #685
> feat: smaller bundle and remove es5 builds since they are not really es5 builds anyway

- package.json
- src/embed.ts
- test-baseurl.html
- yarn.lock
needs https://github.com/vega/vega-tooltip/pull/855
fixes https://github.com/vega/vega-lite/issues/9151
> feat: pass baseurl through to default tooltip handler

- package.json
This should allow esm imports. The `module` field is usually used but some bundlers are not preferring it since exports is standardized in node. https://nodejs.org/api/packages.html#package-entry-points
In the future, we could even get rid of the `module` and `main` in favor of just `exports`.
> feat: add explicit exports

- src/embed.ts
this means we may change the mode from Vega-Lite to Vega if there is a patch
fixes #1336
> fix: apply patch before posting
